import type { Crop } from '../types'

export const CROPS: Record<string, Crop> = {
  tomato: {
    id: 'tomato',
    name: 'トマト',
    nameEn: 'Tomato',
    season: 'summer',
    category: '果菜類',
    plantingMonths: [4, 5],
    harvestMonths: [7, 8, 9],
    optimalTemp: { min: 20, max: 30 },
    frostTolerance: '低',
    revenuePerUnit: 800000,
    costPerUnit: 350000,
    difficulty: 3,
    waterRequirement: '中',
    suitableSoilPH: { min: 6.0, max: 6.8 },
    rotationAvoid: ['ナス', 'ピーマン', 'じゃがいも'],
    description: '高単価が狙える夏の主力野菜。寒暖差で糖度が上がる。',
  },
  cucumber: {
    id: 'cucumber',
    name: 'きゅうり',
    nameEn: 'Cucumber',
    season: 'summer',
    category: '果菜類',
    plantingMonths: [4, 5],
    harvestMonths: [6, 7, 8, 9],
    optimalTemp: { min: 18, max: 28 },
    frostTolerance: '低',
    revenuePerUnit: 600000,
    costPerUnit: 250000,
    difficulty: 2,
    waterRequirement: '高',
    suitableSoilPH: { min: 5.5, max: 7.0 },
    rotationAvoid: ['スイカ', 'メロン', 'かぼちゃ'],
    description: '安定した需要があり、初心者にも栽培しやすい。',
  },
  eggplant: {
    id: 'eggplant',
    name: 'ナス',
    nameEn: 'Eggplant',
    season: 'summer',
    category: '果菜類',
    plantingMonths: [5, 6],
    harvestMonths: [7, 8, 9, 10],
    optimalTemp: { min: 22, max: 30 },
    frostTolerance: '低',
    revenuePerUnit: 550000,
    costPerUnit: 220000,
    difficulty: 2,
    waterRequirement: '中',
    suitableSoilPH: { min: 6.0, max: 6.5 },
    rotationAvoid: ['トマト', 'ピーマン', 'じゃがいも'],
    description: '日本の食卓の定番。産地によるブランド化も可能。',
  },
  edamame: {
    id: 'edamame',
    name: '枝豆',
    nameEn: 'Edamame',
    season: 'summer',
    category: '豆類',
    plantingMonths: [5, 6],
    harvestMonths: [8, 9],
    optimalTemp: { min: 20, max: 28 },
    frostTolerance: '低',
    revenuePerUnit: 400000,
    costPerUnit: 150000,
    difficulty: 2,
    waterRequirement: '中',
    suitableSoilPH: { min: 6.0, max: 7.0 },
    rotationAvoid: ['大豆', '小豆'],
    description: 'ビールの季節に高需要。窒素固定で土壌改良効果も。',
  },
  corn: {
    id: 'corn',
    name: 'とうもろこし',
    nameEn: 'Corn',
    season: 'summer',
    category: '穀類',
    plantingMonths: [4, 5],
    harvestMonths: [7, 8],
    optimalTemp: { min: 22, max: 30 },
    frostTolerance: '低',
    revenuePerUnit: 350000,
    costPerUnit: 120000,
    difficulty: 2,
    waterRequirement: '高',
    suitableSoilPH: { min: 5.5, max: 7.0 },
    rotationAvoid: [],
    description: '北海道の夏の風物詩。直売所で人気が高い。',
  },
  lettuce: {
    id: 'lettuce',
    name: 'レタス',
    nameEn: 'Lettuce',
    season: 'summer',
    category: '葉菜類',
    plantingMonths: [4, 5, 8],
    harvestMonths: [6, 7, 10],
    optimalTemp: { min: 15, max: 20 },
    frostTolerance: '中',
    revenuePerUnit: 500000,
    costPerUnit: 180000,
    difficulty: 3,
    waterRequirement: '高',
    suitableSoilPH: { min: 6.0, max: 7.0 },
    rotationAvoid: ['キク科野菜'],
    description: '冷涼な気候を好む。高原野菜として夏場に高値。',
  },
  cabbage: {
    id: 'cabbage',
    name: 'キャベツ',
    nameEn: 'Cabbage',
    season: 'summer',
    category: '葉菜類',
    plantingMonths: [3, 4, 7, 8],
    harvestMonths: [6, 7, 10, 11],
    optimalTemp: { min: 15, max: 20 },
    frostTolerance: '高',
    revenuePerUnit: 450000,
    costPerUnit: 160000,
    difficulty: 2,
    waterRequirement: '中',
    suitableSoilPH: { min: 6.0, max: 7.5 },
    rotationAvoid: ['ブロッコリー', 'カリフラワー'],
    description: '安定需要の定番野菜。作期が長く計画的な出荷が可能。',
  },
  asparagus: {
    id: 'asparagus',
    name: 'アスパラガス',
    nameEn: 'Asparagus',
    season: 'summer',
    category: '茎菜類',
    plantingMonths: [3, 4],
    harvestMonths: [4, 5, 6],
    optimalTemp: { min: 15, max: 25 },
    frostTolerance: '高',
    revenuePerUnit: 900000,
    costPerUnit: 300000,
    difficulty: 4,
    waterRequirement: '中',
    suitableSoilPH: { min: 6.0, max: 7.0 },
    rotationAvoid: [],
    description: '高単価の多年生作物。一度植えると10年以上収穫可能。',
  },
  onion: {
    id: 'onion',
    name: '玉ねぎ',
    nameEn: 'Onion',
    season: 'summer',
    category: '根菜類',
    plantingMonths: [9, 10],
    harvestMonths: [6, 7],
    optimalTemp: { min: 15, max: 20 },
    frostTolerance: '高',
    revenuePerUnit: 400000,
    costPerUnit: 140000,
    difficulty: 2,
    waterRequirement: '中',
    suitableSoilPH: { min: 6.0, max: 7.0 },
    rotationAvoid: ['ねぎ', 'にんにく'],
    description: '北海道の主力野菜。貯蔵性が高く、出荷調整が容易。',
  },
  potato: {
    id: 'potato',
    name: '馬鈴薯（じゃがいも）',
    nameEn: 'Potato',
    season: 'summer',
    category: '根菜類',
    plantingMonths: [4, 5],
    harvestMonths: [7, 8, 9],
    optimalTemp: { min: 15, max: 22 },
    frostTolerance: '低',
    revenuePerUnit: 350000,
    costPerUnit: 130000,
    difficulty: 2,
    waterRequirement: '中',
    suitableSoilPH: { min: 5.0, max: 6.5 },
    rotationAvoid: ['トマト', 'ナス'],
    description: '北海道を代表する作物。品種による差別化も可能。',
  },
  winter_spinach: {
    id: 'winter_spinach',
    name: '寒締めほうれん草',
    nameEn: 'Winter Spinach',
    season: 'winter',
    category: '葉菜類',
    plantingMonths: [9, 10],
    harvestMonths: [12, 1, 2],
    optimalTemp: { min: -5, max: 15 },
    frostTolerance: '極高',
    revenuePerUnit: 700000,
    costPerUnit: 200000,
    difficulty: 3,
    waterRequirement: '低',
    suitableSoilPH: { min: 6.5, max: 7.5 },
    rotationAvoid: ['ビート'],
    description: '寒さで糖度が上がり、通常の2倍以上の価格で取引される。',
  },
  winter_komatsuna: {
    id: 'winter_komatsuna',
    name: '寒締め小松菜',
    nameEn: 'Winter Komatsuna',
    season: 'winter',
    category: '葉菜類',
    plantingMonths: [9, 10],
    harvestMonths: [12, 1, 2],
    optimalTemp: { min: -3, max: 15 },
    frostTolerance: '高',
    revenuePerUnit: 550000,
    costPerUnit: 180000,
    difficulty: 2,
    waterRequirement: '低',
    suitableSoilPH: { min: 6.0, max: 7.0 },
    rotationAvoid: ['キャベツ', 'ブロッコリー'],
    description: '寒さに強く、冬期のハウス栽培でも暖房費を抑えられる。',
  },
  snow_carrot: {
    id: 'snow_carrot',
    name: '雪下人参',
    nameEn: 'Snow Carrot',
    season: 'winter',
    category: '根菜類',
    plantingMonths: [7, 8],
    harvestMonths: [1, 2, 3],
    optimalTemp: { min: -5, max: 15 },
    frostTolerance: '極高',
    revenuePerUnit: 650000,
    costPerUnit: 190000,
    difficulty: 3,
    waterRequirement: '低',
    suitableSoilPH: { min: 5.5, max: 7.0 },
    rotationAvoid: ['セロリ', 'パセリ'],
    description: '雪の下で越冬させることで甘みが増す。プレミアム野菜として人気。',
  },
  winter_leek: {
    id: 'winter_leek',
    name: '冬ねぎ',
    nameEn: 'Winter Leek',
    season: 'winter',
    category: '葉菜類',
    plantingMonths: [4, 5],
    harvestMonths: [11, 12, 1, 2],
    optimalTemp: { min: -10, max: 20 },
    frostTolerance: '極高',
    revenuePerUnit: 600000,
    costPerUnit: 170000,
    difficulty: 2,
    waterRequirement: '中',
    suitableSoilPH: { min: 6.0, max: 7.0 },
    rotationAvoid: ['玉ねぎ', 'にんにく'],
    description: '飛騨ねぎのような地域ブランドが確立している。冬の鍋需要で高値。',
  },
  daikon: {
    id: 'daikon',
    name: '大根',
    nameEn: 'Daikon',
    season: 'winter',
    category: '根菜類',
    plantingMonths: [8, 9],
    harvestMonths: [11, 12, 1],
    optimalTemp: { min: 5, max: 20 },
    frostTolerance: '高',
    revenuePerUnit: 400000,
    costPerUnit: 130000,
    difficulty: 2,
    waterRequirement: '中',
    suitableSoilPH: { min: 5.5, max: 7.0 },
    rotationAvoid: ['カブ', 'キャベツ'],
    description: '冬の定番野菜。漬物用や加工用としても需要が安定。',
  },
  hakusai: {
    id: 'hakusai',
    name: '白菜',
    nameEn: 'Chinese Cabbage',
    season: 'winter',
    category: '葉菜類',
    plantingMonths: [8, 9],
    harvestMonths: [11, 12, 1],
    optimalTemp: { min: 5, max: 20 },
    frostTolerance: '高',
    revenuePerUnit: 380000,
    costPerUnit: 140000,
    difficulty: 2,
    waterRequirement: '中',
    suitableSoilPH: { min: 6.0, max: 7.0 },
    rotationAvoid: ['キャベツ', 'ブロッコリー'],
    description: '鍋の季節に高需要。貯蔵性があり、出荷調整が可能。',
  },
  turnip: {
    id: 'turnip',
    name: 'かぶ',
    nameEn: 'Turnip',
    season: 'winter',
    category: '根菜類',
    plantingMonths: [8, 9],
    harvestMonths: [10, 11, 12],
    optimalTemp: { min: 5, max: 20 },
    frostTolerance: '高',
    revenuePerUnit: 420000,
    costPerUnit: 150000,
    difficulty: 2,
    waterRequirement: '中',
    suitableSoilPH: { min: 5.5, max: 7.0 },
    rotationAvoid: ['大根'],
    description: '飛騨紅かぶなど、地域品種のブランド化が進んでいる。',
  },
  wheat: {
    id: 'wheat',
    name: '小麦',
    nameEn: 'Wheat',
    season: 'winter',
    category: '穀類',
    plantingMonths: [9, 10],
    harvestMonths: [7, 8],
    optimalTemp: { min: 5, max: 20 },
    frostTolerance: '極高',
    revenuePerUnit: 80000,
    costPerUnit: 40000,
    difficulty: 1,
    waterRequirement: '低',
    suitableSoilPH: { min: 6.0, max: 7.0 },
    rotationAvoid: [],
    description: '北海道の基幹作物。輪作体系の重要な構成要素。',
  },
}

export function getCrop(id: string): Crop | undefined {
  return CROPS[id]
}

export function getSummerCrops(): Crop[] {
  return Object.values(CROPS).filter((crop) => crop.season === 'summer')
}

export function getWinterCrops(): Crop[] {
  return Object.values(CROPS).filter((crop) => crop.season === 'winter')
}

export function getCropProfit(id: string): number {
  const crop = CROPS[id]
  if (!crop) return 0
  return crop.revenuePerUnit - crop.costPerUnit
}

export function getCropsByCategory(category: string): Crop[] {
  return Object.values(CROPS).filter((crop) => crop.category === category)
}

export const CROP_CATEGORIES = [
  '果菜類',
  '葉菜類',
  '根菜類',
  '豆類',
  '茎菜類',
  '穀類',
] as const
